// Auto-generated by scripts/generate-lagrum.cjs from Brå "Klassificering av brott"
// Do not edit manually — re-generate with:
//   node scripts/generate-lagrum.cjs bra-klassificering.pdf > src/lib/lagrumMappings.ts
//
// The matcher lives in src/lib/lagrumMatch.ts (hand-maintained) and consults
// src/lib/lagrumOverrides.ts for hand-curated additions and blocklist.

import type { Sakomrade } from "./sakomrade";

export interface LagrumEntry {
  sakomrade: Sakomrade;
  primart_lagrum: string[];
  alternativa_lagrum?: string[];
}

export const mappings: Record<string, LagrumEntry> = {
  "alkohollagen, olovlig befattning med sprit genom förvärv, innehav m.m. av sprit eller spritdrycker som är olovligt tillverkade": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "alkohollagen, olovlig vin- och öltillverkning": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "allmänfarlig vårdslöshet, annan allmänfarlig vårdslöshet": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "allmänfarlig vårdslöshet, vållande av brand, ej mordbrand, skadegörelse eller brand utan misstanke om brott": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "allmänfarlig ödeläggelse": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "allmänfarlig ödeläggelse genom sprängning": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "allmänfarliga brott": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap. 1–10 §"],
  },
  "annan skadegörelse (ej klotter)": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "annat brott mot vapenlagen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "annonsbedrägeri, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "annonsbedrägeri, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "annonsbedrägeri, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "annonsbedrägeri, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "arbetsmiljölagen, åsidosättande av föreläggande eller förbud enligt arbetsmiljölagen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "artskyddsbrott": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "barnadråp": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 3 §"],
  },
  "barnfridsbrott": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 3 §"],
  },
  "barnpornografibrott": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "barnäktenskapsbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "bedrägeri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9 kap. 1 §"],
  },
  "bedrägeri genom social manipulation, av annan typ, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "bedrägeri genom social manipulation, av annan typ, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "bedrägeri genom social manipulation, av annan typ, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "bedrägeri genom social manipulation, av annan typ, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "bedrägeri mot eu:s finansiella intressen": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "befogenhetsbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "befogenhetsbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "befogenhetsbedrägeri, bedrägeri genom social manipulation, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "befogenhetsbedrägeri, bedrägeri genom social manipulation, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "behörighetsmissbruk": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "beteendebrott i trafiken": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "bidragsbrott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Bidragsbrottslagen (2007:612) 2 §"],
  },
  "bidragsbrott av normalgraden mot arbetslöshetskassorna och arbetsförmedlingen": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott av normalgraden mot försäkringskassan": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott av normalgraden mot kommunerna": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott av normalgraden mot ppm, csn och migrationsverket": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, grovt, mot arbetslöshetskassorna och arbetsförmedlingen": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, grovt, mot försäkringskassan": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, grovt, mot kommunerna": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, grovt, mot ppm, csn och migrationsverket": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, ringa, mot a-kassorna och länsarbetsnämnderna/arbetsförmedlingen": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, ringa, mot försäkringskassan": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, ringa, mot kommunerna": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bidragsbrott, ringa, mot ppm, csn och migrationsverket": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "bilbältesbrott": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "bokföringsbrott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap. 5 §"],
  },
  "bokföringsbrott, av normalgraden, ej konkurs, försenad eller avsaknad av årsredovisning": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, av normalgraden, ej konkurs, övriga brott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, av normalgraden, konkurs, försenad eller avsaknad av årsredovisning": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, av normalgraden, konkurs, övriga brott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, grovt, ej konkurs": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, grovt, konkurs": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, ringa, ej konkurs, försenad eller avsaknad av årsredovisning": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, ringa, ej konkurs, övriga brott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, ringa, konkurs, försenad eller avsaknad av årsredovisning": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "bokföringsbrott, ringa, konkurs, övriga brott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "brand utan misstanke om brott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brott mot 22:a kap brb. 2206 folkmord 2207 brott mot mänskligheten": {
    sakomrade: "Landsförräderi",
    primart_lagrum: ["BrB 22 kap."],
  },
  "brott mot allmän ordning": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap. 1–6 §"],
    alternativa_lagrum: ["BrB 16 kap. 8–13 §","BrB 16 kap. 15 §"],
  },
  "brott mot allmän verksamhet m.m.": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap. 1 §"],
    alternativa_lagrum: ["BrB 17 kap. 2 §","BrB 17 kap. 4 §","BrB 17 kap. 5 §","BrB 17 kap. 7–13 §","BrB 17 kap. 15 §"],
  },
  "brott mot borgenärer m.m.": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap. 1–5 §"],
  },
  "brott mot bulvan-/målvaktsbestämmelser": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "brott mot det industriella rättsskyddet": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "brott mot familj": {
    sakomrade: "Brott mot familj",
    primart_lagrum: ["BrB 7 kap. 1–4 §"],
  },
  "brott mot föreskrift om förbud, som syftar att genomföra internationella sanktioner (enligt rådets förordning (eg) 881/2002, om särskilda restriktiva åtgärder i syfte att bekämpa terrorism), 8 och 15 §": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brott mot föreskrift som genomför internationella sanktioner (enligt rådets förordning (eg) 2580/2001, om särskilda restriktiva åtgärder i syfte att bekämpa terrorism), 8 och 15 § 7016 brott mot föreskrift som genomför internationella sanktioner, övriga fall (än finansiering av terrorism), 8 och 15 §": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brott mot lagen med förbud mot könsstympning av kvinnor": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brott mot låneförbudet m.m.": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "brott mot medborgerlig frihet": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap."],
  },
  "brott mot områdesskydd, förseelse mot områdesskydd": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "brott mot tystnadsplikt": {
    sakomrade: "Tjänstebrott",
    primart_lagrum: ["BrB 20 kap."],
  },
  "brott mot upphovsrätten ej genom fildelning": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brott mot upphovsrätten genom fildelning": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "brukande av osann urkund, gäller pass": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap."],
  },
  "dataintrång": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 9 c §"],
  },
  "deltagande i en terroristorganisation": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "djurplågeri": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "dopningslagen, bruk": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Dopningslagen"],
  },
  "dopningslagen, framställning": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Dopningslagen"],
  },
  "dopningslagen, innehav": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Dopningslagen"],
  },
  "dopningslagen, överlåtelse": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Dopningslagen"],
  },
  "drunkning": {
    sakomrade: "Brott mot utlänningslagen",
    primart_lagrum: ["Utlänningslagen"],
  },
  "dråp": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 2 §"],
  },
  "egenmäktighet med barn": {
    sakomrade: "Brott mot familj",
    primart_lagrum: ["BrB 7 kap."],
  },
  "egenmäktigt förfarande": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 8 §"],
  },
  "fakturabedrägeri, med kontakt, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, med kontakt, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, med kontakt, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, med kontakt, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, utan kontakt, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, utan kontakt, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, utan kontakt, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fakturabedrägeri, utan kontakt, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "falsk och vårdslös beskyllning": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap."],
  },
  "falskt larm": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "fartöverträdelse till sjöss": {
    sakomrade: "Sjöfartsbrott",
    primart_lagrum: ["Sjölagen"],
  },
  "finansiering av en terroristorganisation, eller en person eller sammanslutning av personer som begår eller på annat sätt medverkar till terroristbrott eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "finansiering för att begå eller på annat sätt medverka till annan särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "finansiering för att begå eller på annat sätt medverka till terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "fiskelagen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "folkbokföringslagen, folkbokföringsbrott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Folkbokföringslagen"],
  },
  "fordringsbedrägeri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9 kap. 1–3 §"],
  },
  "fornminnesbrott genom att tillägna sig, förvärva, gömma, skada, ändra eller avyttra fornfynd": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "fornminnesbrott, övriga brott": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "framkallande av fara för annan, för arbetstagare": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "framkallande av fara för annan, i trafiken och övriga fall": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "främjande av olovligt spel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "fullbordad våldtäkt": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "fullbordat mord eller dråp": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 1 §"],
    alternativa_lagrum: ["BrB 3 kap. 2 §"],
  },
  "fullbordat mord, dråp eller misshandel med dödlig utgång": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "fullbordat tillgrepp av motordrivet fortskaffningsmedel, bil": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "fyndförseelse": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "förfalskning": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap. 1 §"],
  },
  "förfalskningsbrott": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap. 1–11 §"],
  },
  "förfalskningsbrott, annan legitimationshandling": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förfalskningsbrott, check": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förfalskningsbrott, handling som använts för illegal resa ut, från eller in i sverige: pass, resedokument, främlingspass, stickers för visering och uppehållstillstånd": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förfalskningsbrott, svenskt körkort": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förfalskningsbrott, tjänste- eller identitetskort": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förfalskningsbrott, övrig urkundsförfalskning": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "förgöring": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "förolämpning mot tjänsteman": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "förskingring": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 10 kap. 1 §"],
  },
  "förskingring och annan trolöshet": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 10 kap. 1–8 §"],
  },
  "förskingring, ringa förskingring, grov förskingring": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "försvunnen person i fjällen": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "försvunnen person, barn utan vårdnadshavare": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "försvunnen person, ej i fjällen": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "försvårande av konkurs eller exekutiv förrättning": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "försäkringsbedrägeri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "försök till tillgrepp av motordrivet fortskaffningsmedel, bil": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "försök till våldtäkt": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "försök, förberedelse och stämpling till mord eller dråp": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "ge utbildning för terrorism eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "givande av muta": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "gravfridsbrott": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "grov": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 5 §"],
  },
  "grov fridskränkning": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "grov fridskränkning, olaga förföljelse, m. m.": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 4 §"],
  },
  "grov kvinnofridskränkning": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "grov misshandel": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 6 §"],
  },
  "grov mordbrand": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap. 2 §"],
  },
  "grov narkotikasmuggling, synnerligen grov narkotikasmuggling": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "grov skadegörelse": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap. 3 §"],
  },
  "grov smuggling av dopningsmedel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov smuggling av explosiv vara, synnerligen grov smuggling av explosiv vara": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov smuggling av hälsofarliga varor": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov smuggling av övriga varor, ej dopningsmedel, alkohol, tobak, icke narkotikaklassade läkemedel eller hälsofarliga varor": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "grov smuggling, alkohol- eller tobaksvaror 4061 4063 4066 4067 4068 tullbrott, vårdslös tullredovisning, alkohol- eller tobaksvaror olovlig befattning med smuggelgods, alkohol- eller tobaksvaror olovlig befattning med smuggelgods, narkotika olovlig befattning med punktskattepliktiga varor olovlig förflyttning av punktskattepliktiga varor": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "grov smuggling, icke narkotikaklassade läkemedel": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "grov stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 4 §"],
  },
  "grov urkundsförfalskning": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap. 3 §"],
  },
  "grov vapensmuggling, synnerligen grov vapensmuggling, av annat vapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov vapensmuggling, synnerligen grov vapensmuggling, av automatvapen (inkl. kulsprutepistol)": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov vapensmuggling, synnerligen grov vapensmuggling, av jaktvapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov vapensmuggling, synnerligen grov vapensmuggling, av pistol, revolver start-, signalvapen och tårgasvapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "grov våldtäkt": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 1 §"],
  },
  "grovt barnfridsbrott": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 3 §"],
  },
  "grovt bedrägeri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9 kap. 3 §"],
  },
  "grovt bokföringsbrott": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap. 5 §"],
  },
  "grovt fordringsbedrägeri, ej internationell anknytning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "grovt fordringsbedrägeri, internationell anknytning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "grovt narkotikabrott": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen (1968:64) 3 §"],
  },
  "grovt rattfylleri": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen (1951:649) 4 a §"],
  },
  "grovt skattebrott, avseende enbart mervärdesskattelagen, vid gränsöverskridande handel eller både handel inom landet och gränsöverskridande handel": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "grovt skattebrott, avseende enbart mervärdesskattelagen, vid handel endast inom landet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "grovt skattebrott, avseende övrig skattelagstiftning": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "grovt vapenbrott": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen (1996:67) 9 kap."],
  },
  "grovt vapenbrott, synnerligen grovt vapenbrott, innehav av annat vapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "grovt vapenbrott, synnerligen grovt vapenbrott, innehav av automatvapen (inkl. kulsprutepistol)": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "grovt vapenbrott, synnerligen grovt vapenbrott, innehav av pistol, revolver, start-, signalvapen och tårgasvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "grovt vapenbrott, synnerligen grovt vapenbrott; innehav av jaktvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "grovt vapenbrott, synnerligen grovt vapenbrott; överlåtelse eller utlåning av skjutvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "handel med inflytande och/eller vårdslös finansiering av mutbrott": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "handling av barn": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 8 §"],
    alternativa_lagrum: ["BrB 6 kap. 9 §"],
  },
  "har anställning eller bedriver verksamhet utan att inneha arbetstillstånd": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "har utlänning anställd som inte har rätt att vistas i sverige eller som saknar arbetstillstånd": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "hastighetsöverträdelse på väg": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "hedersförtryck": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "hemfridsbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "hemfridsbrott, olovlig identitetsanvändning m. m.": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 6–6 §"],
  },
  "hets mot folkgrupp": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "hindrande av elektronisk övervakning av vistelseförbud 4145 överträdelse av tillträdesförbud till butiker, badanläggningar och bibliotek": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["Kontaktförbudslagen"],
  },
  "hindrande eller försvårande av elektronisk övervakning": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["Kontaktförbudslagen"],
  },
  "hjälp till utlänning att olovligen uppehålla sig i sverige, annan eu-stat eller schengenområdet": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "hot mot tjänsteman": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap. 1 §"],
  },
  "hot mot tjänsteman, angrepp mot tjänsteman": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "häleri med vanemässig inriktning eller av stor omfattning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "högmålsbrott": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap. 1 §"],
    alternativa_lagrum: ["BrB 18 kap. 3–6 §"],
  },
  "identitetsbedrägeri, av annan typ, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, av annan typ, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, av annan typ, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, av annan typ, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, köp, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, köp, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, köp, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, köp, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, lån, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, lån, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, lån, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "identitetsbedrägeri, lån, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "illegal rovdjursjakt av varg, björn, järv, lodjur och kungsörn": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "inbrottsstöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 4 §"],
  },
  "inbrottsstöld i fritidshus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, fullbordat, i annan typ av bostad än villa, radhus, lägenhet eller fritidshus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, fullbordat, i lägenhet": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, fullbordat, i villa/radhus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, försök, i annan typ av bostad än villa, radhus, lägenhet eller fritidshus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, försök, i lägenhet": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "inbrottsstöld, försök, i villa/radhus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "insiderbrott": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "insiderbrott, grovt brott": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "intrång i förvar": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "investeringsbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "investeringsbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "investeringsbedrägeri, bedrägeri genom social manipulation, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "investeringsbedrägeri, bedrägeri genom social manipulation, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "involverande av en underårig i brottslighet": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "jaktlagen, jaktbrott": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "kontakt för att träffa en flicka under i sexuellt syfte": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap."],
  },
  "kontakt för att träffa en pojke under i sexuellt syfte": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap."],
  },
  "kontakt för att träffa ett barn i sexuellt syfte": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 10 §"],
  },
  "koppleri": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap."],
  },
  "kortbedrägeri, med fysiskt kort, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "kortbedrägeri, med fysiskt kort, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "kortbedrägeri, med fysiskt kort, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "kortbedrägeri, med fysiskt kort, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "kortbedrägeri, utan fysiskt kort, ej internationell anknytning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "kortbedrägeri, utan fysiskt kort, internationell anknytning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "krigsförbrytelse": {
    sakomrade: "Landsförräderi",
    primart_lagrum: ["BrB 22 kap."],
  },
  "kränkande fotografering": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "köp av sexuell handling": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "köp av sexuell tjänst, koppleri": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 11 §"],
    alternativa_lagrum: ["BrB 6 kap. 12 §"],
  },
  "lag om förbud mot vissa hälsofarliga varor, innehav": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "lag om förbud mot vissa hälsofarliga varor, övriga brott": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "lag om handel med läkemedel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "lag om handel med vissa receptfria läkemedel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "lag om tobak och liknande produkter": {
    sakomrade: "Alkohol- och punktskattebrott",
    primart_lagrum: ["Tobakslagen"],
  },
  "lag om tobaksfria nikotinprodukter": {
    sakomrade: "Alkohol- och punktskattebrott",
    primart_lagrum: ["Tobakslagen"],
  },
  "lagen om kontroll av narkotika, bedriver verksamhet utan tillstånd etc.": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "lagen om näringsförbud, överträdelse av näringsförbud": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "lagen om åtgärder mot föroreningar från fartyg": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "lbe, hantering, överföring, import eller export av brandfarliga eller explosiva varor utan att vidta försiktighetsmått": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Lagen om brandfarliga och explosiva varor"],
  },
  "lbe, hantering, överföring, import eller export av explosiva varor utan tillstånd": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Lagen om brandfarliga och explosiva varor"],
  },
  "lbe, hantering, överföring, import eller export av explosiva varor utan tillstånd, grovt brott och synnerligen grovt brott": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Lagen om brandfarliga och explosiva varor"],
  },
  "lbe, yrkesmässig hantering eller hantering av större mängd brandfarliga varor utan tillstånd": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Lagen om brandfarliga och explosiva varor"],
  },
  "läkemedelslag": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "lönegarantibedrägeri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "marknadsmanipulation": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Marknadsmissbrukslagen"],
  },
  "marknadsmanipulation, grovt brott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Marknadsmissbrukslagen"],
  },
  "mened": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap. 1 §"],
  },
  "mened, osann partsutsaga eller ovarsam utsaga": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap."],
  },
  "miljöbalken, bristfällig miljöinformation": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, försvårande av miljökontroll": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, miljöbrott": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, miljöfarlig kemikaliehantering, olovlig kemikaliehantering, kemikalieregistreringsbrott": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, nedskräpning": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, otillåten hantering av en invasiv främmande art": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, otillåten miljöverksamhet genom avsaknad av tillstånd etc.": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "miljöbalken, otillåten miljöverksamhet genom brytande mot villkor i tillstånd etc.": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "missbruk av larmordning": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "missbruk av urkund avseende pass, resedokument, främlingspass, stickers för visering och uppehållstillstånd, som berör migrationsärenden": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap."],
  },
  "misshandel": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 5 §"],
    alternativa_lagrum: ["BrB 3 kap. 6 §"],
  },
  "misshandel, annan än grov": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "misshandel, ej grov": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "misshandel, grov": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "mord": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 1 §"],
  },
  "mord, dråp, barnadråp": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 1 §"],
    alternativa_lagrum: ["BrB 3 kap. 2 §","BrB 3 kap. 3 §"],
  },
  "mordbrand": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "myteri": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "människoexploatering": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för krigstjänst med barn under": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för krigstjänst med person": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för organhandel med barn under": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för organhandel med person": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för sexuella ändamål med barn under": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för sexuella ändamål med person": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för tiggeri med barn under": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för tiggeri med person": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för tvångsarbete med barn under": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för tvångsarbete med person": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människohandel för övriga ändamål med barn under 0479 0480 0481 0482 0483 människohandel för övriga ändamål med person olovlig identitetsanvändning": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människorov": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "människosmuggling": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "narkotikabrott": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen (1968:64) 1 §"],
  },
  "narkotikasmuggling, ej grov, olovlig införsel av narkotika, olovlig utförsel av narkotika": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "narkotikastrafflagen, bruk": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "narkotikastrafflagen, framställning": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "narkotikastrafflagen, innehav": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "narkotikastrafflagen, överlåtelse": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "näringspenningtvätt": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "näringspenningtvätt, grovt brott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "näringspenningtvätt, ringa brott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "oaktsam uppmaning till självmord": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "oaktsam våldtäkt": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 1 §"],
  },
  "oaktsamt sexuellt övergrepp": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "obehörigt röjande av insiderinformation": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Marknadsmissbrukslagen"],
  },
  "ocker": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "offentlig uppmaning till terrorism eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ofredande": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 7 §"],
  },
  "ofredande mot grupp": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "olaga diskriminering": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "olaga frihetsberövande": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 2 §"],
  },
  "olaga förföljelse": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "olaga hot": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 5 §"],
  },
  "olaga hot mot grupp": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "olaga innehav av knivar m.m. på allmän plats, överlåtelse eller saluhållande av knivar m.m.": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Knivlagen"],
  },
  "olaga integritetsintrång": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 6 §"],
    alternativa_lagrum: ["BrB 4 kap. 6 §"],
  },
  "olaga intrång": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "olaga tvång": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 4 §"],
  },
  "olovlig avlyssning m.m.": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "olovlig befattning med betalningsverktyg": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "olovlig befattning med smuggelgods": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "olovlig befattning med smuggelgods, icke narkotikaklassade läkemedel": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "olovlig befattning med sprit genom tillverkning": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "olovlig befattning med övriga varor": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "olovlig försäljning av alkohol": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "olovlig försäljning av teknisk sprit m.m.": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "olovlig kårverksamhet": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap."],
  },
  "olovlig körning": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "olovlig körning, tillåtit olovlig körning etc.": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "olovlig körning, åsidosatt föreskrift": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "olovlig spelverksamhet": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "olovlig underrättelseverksamhet": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "olovlig underrättelseverksamhet mot främmande makt": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "olovlig underrättelseverksamhet mot sverige": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "olovlig vistelse i sverige": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "olovligt anskaffande av alkohol, olovlig hantering av alkohol": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "olovligt brukande": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "olovligt förfogande, annat olovligt förfogande": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "olovligt förfogande, över avbetalningsgods": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "ordningslagen, brott mot allmänna sammankomster och offentliga tillställningar": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ordningslagen, obehörigt beträdande av spelplanen eller motsvarande område avsett för idrottsutövning, vid idrottsarrangemang": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ordningslagen, olovligt innehav, användning av pyrotekniska varor vid idrottsarrangemang på idrottsanläggning": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ordningslagen, övriga brott vid idrottsarrangemang": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "oredlighet mot borgenärer": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "organiserande av människosmuggling": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "otillbörlig påverkan vid adoption av barn": {
    sakomrade: "Brott mot familj",
    primart_lagrum: ["BrB 7 kap."],
  },
  "otillbörligt gynnande av borgenär": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "otillbörligt verkande vid röstning, tagande av otillbörlig förmån vid röstning": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "otillåten gränsöverskridande avfallstransport, inom, till och från eu": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "otillåten nationell avfallstransport": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "penningförfalskning, olovlig befattning med falska pengar, brukande av det förfalskade, olaga spridande av efterbildning": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "penningtvättsbrott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "penningtvättsbrott, grovt brott": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "penningtvättsförseelse": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Penningtvättslagen"],
  },
  "personskada utan misstanke om brott till följd av polisverksamhet eller under vistelse i polisarrest": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "rattfylleri": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "rekrytering till terrorism eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "resa för terrorism eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ringa misshandel": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 5 §"],
  },
  "ringa narkotikabrott": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen (1968:64) 2 §"],
  },
  "ringa stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 2 §"],
  },
  "romansbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "romansbedrägeri, bedrägeri genom social manipulation, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "romansbedrägeri, bedrägeri genom social manipulation, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "romansbedrägeri, bedrägeri genom social manipulation, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 5 §"],
    alternativa_lagrum: ["BrB 8 kap. 6 §"],
  },
  "rån med skjutvapen, mot privatperson": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån mot privatperson, med skjutvapen": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån mot privatperson, under, med skjutvapen": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån mot privatperson, under, utan skjutvapen": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån mot privatperson, utan skjutvapen": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån utan skjutvapen, mot privatperson": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, mot bank/växlingskontor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, mot butik": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, mot taxi": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, mot värdebefordran": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, mot värdetransport": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, med skjutvapen, övrigt rån": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, mot bank/växlingskontor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, mot butik": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, mot taxi": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, mot värdebefordran": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, mot värdetransport": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "rån, utan skjutvapen, övrigt rån": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "röjande av hemlig uppgift i internationellt samarbete": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "sabotage": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap. 4 §"],
  },
  "sabotage mot blåljusverksamhet": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "samlag med avkomling eller syskon": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 7 §"],
  },
  "samröre med en terroristorganisation": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "sexuellt ofredande": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt ofredande, sexuellt ofredande mot barn": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 10 §"],
  },
  "sexuellt utnyttjande av barn, sexuellt övergrepp mot barn": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 5 §"],
    alternativa_lagrum: ["BrB 6 kap. 6 §"],
  },
  "sexuellt utnyttjande av flicka under, ej på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av flicka under, på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av flicka, ej på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av flicka, på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av pojke under, ej på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av pojke under, på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av pojke, ej på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt utnyttjande av pojke, på internet": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "sexuellt övergrepp": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "signaturförfalskning, brukande av det förfalskade": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "självmord": {
    sakomrade: "Brott mot utlänningslagen",
    primart_lagrum: ["Utlänningslagen"],
  },
  "självständigt förverkande": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "sjöfylleri": {
    sakomrade: "Sjöfartsbrott",
    primart_lagrum: ["Sjölagen"],
  },
  "skadegörelse": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap. 1 §"],
  },
  "skadegörelse, bilbrand eller brand på annat motorfordon (ej mordbrand, 1301)": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelse, genom brand (ej på motorfordon)": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelse, klotter mot kollektivtrafiken": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelse, mot stat, kommun, landsting, ej klotter": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelse, på motorfordon, ej genom brand": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelse, övrigt klotter": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "skadegörelsebrott": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap. 1–4 §"],
  },
  "skattebrott, skatteförseelse, avseende enbart mervärdesskattelagen, vid gränsöverskridande handel eller både handel inom landet och gränsöverskridande handel": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "skattebrott, skatteförseelse, avseende enbart mervärdesskattelagen, vid handel endast inom landet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "skattebrott, skatteförseelse, avseende övrig skattelagstiftning": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "skattebrottslagen, försvårande av skattekontroll": {
    sakomrade: "Skattebrott",
    primart_lagrum: ["Skattebrottslagen"],
  },
  "skattebrottslagen, skatteavdragsbrott": {
    sakomrade: "Skattebrott",
    primart_lagrum: ["Skattebrottslagen"],
  },
  "skattebrottslagen, skatteredovisningsbrott, vårdslös skatteredovisning": {
    sakomrade: "Skattebrott",
    primart_lagrum: ["Skattebrottslagen"],
  },
  "skattebrottslagen, vårdslös skatteuppgift": {
    sakomrade: "Skattebrott",
    primart_lagrum: ["Skattebrottslagen"],
  },
  "skyddslag": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "smitning från trafikolycksplats, med betydande materialskador, personskador eller dödligt utfall": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "smitning från trafikolycksplats, med inga eller lindriga material- och personskador": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "smitning parkeringsskada": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "smuggling av explosiv vara, ej grovt, olovlig in- och utförsel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "smuggling, olovlig in- och utförsel av alkohol- eller tobaksvaror": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "smuggling, olovlig in- och utförsel av dopningsmedel": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "smuggling, olovlig in- och utförsel av hälsofarliga varor": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "smuggling, olovlig in- och utförsel av icke narkotikaklassade läkemedel": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "smuggling, olovlig in- och utförsel av övriga varor, ej dopningsmedel, alkohol, tobak, icke narkotikaklassade läkemedel eller hälsofarliga varor": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "snyltningsbrott": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "spelfusk": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "spioneri, grovt spioneri": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "spridande av gift eller smitta": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 1 §"],
  },
  "stöld (även genom inbrott)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 1 §"],
    alternativa_lagrum: ["BrB 8 kap. 2 §","BrB 8 kap. 4 §"],
  },
  "stöld av annat ej motordrivet fortskaffningsmedel": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av båtmotor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av diesel, ur fordonstank (även entreprenadmaskin m.m.)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av diesel, ur större tankar (ej kopplade till fordon)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av drivmedel (även diesel), ej genom smitning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av drivmedel (även diesel), från bensinstation (genom smitning)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av elsparkcykel": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 1 §"],
    alternativa_lagrum: ["BrB 8 kap. 2 §","BrB 8 kap. 4 §"],
  },
  "stöld av skjutvapen, ammunition och sprängämne från militärt förråd, oavsett plats": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne från skytteorganisations lokal eller förråd": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne från sprängämnesförråd, ej militärt": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, från vapenhandels lokal eller förråd": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, i bostad, ej fritidshus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, i fritidshus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, inom militärförläggning, oavsett förläggningstyp": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, ur motorfordon": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld av skjutvapen, ammunition och sprängämne, övrig stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld från cykel": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott av kulturföremål från kyrka, museum, hembygdsgård, konsthall, bibliotek och arkiv": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från apotek, apoteks- och läkemedelsförråd": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från butik, även i anslutning till bensinstation, varuhus, kommersiell utställningslokal": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från byggplats, från bod, tillfällig barack, container, vagn eller liknande på byggplats": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från fabrik, lager, verkstad, ej bilverkstad": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från garage, även i anslutning till bensinstation, bilverkstad": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från hamnområde": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från kiosk, automat, skyltskåp": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från kontor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från källare, vind": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från läkar- eller tandläkarpraktik, sjukhus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott från militärförläggning, militärt förråd": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott i biograf, teater, nöjes-, samlings- och ungdomslokal": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott i hotell, pensionat eller liknande": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott i idrotts-, bad- och sportanläggning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott i kafé, konditori, restaurang, näringsställe": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott i skola, bibliotek, undervisningslokal, förskola, fritidshem": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld genom inbrott, annan stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld under övrig yrkesmässig transport, ej fickstöld eller yrkesmässig godsbefordran": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld ur eller från lastbil, släpfordon, järnvägsvagn, avsedd för yrkesmässig godsbefordran": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld ur eller från motordrivet fordon, släpfordon och husvagn (ej motorredskap), av endast andra föremål (ej fast interiör/exteriör)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld ur eller från motordrivet fordon, släpfordon och husvagn (ej motorredskap), av fast interiör/exteriör, eller stöld av både fast interiör/exteriör och andra föremål": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld ur och från båt, ej båtmotor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld utan inbrott, från kontor": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott av kulturföremål från kyrka, museum, hembygdsgård, konsthall, bibliotek och arkiv": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott från byggplats, bod, tillfällig barack, container, vagn eller liknande på byggplats": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott från fabrik, lager, verkstad": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, annan fickstöld, stöld ur eller av persedel någon bär med sig, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, annan fickstöld, stöld ur eller av persedel någon bär med sig, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, annan stöld": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från bostad, ej fritidshus, ej hos": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från bostad, ej fritidshus, hos": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från butik, även i anslutning till bensinstation, varuhus, kommersiell utställningslokal": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från hamnområde": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från källare och vind": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från läkar- och tandläkarpraktik, sjukhus": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, från militärförläggning, militärt förråd": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, i biograf, teater, nöjes-, samlings- och ungdomslokal": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, i hotell, pensionat eller liknande": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, i idrotts-, bad- och sportanläggning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, i kafé, konditori, restaurang, näringsställe": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, i skola, bibliotek, undervisningslokal, förskola, fritidshem": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, inom campingplats, strandbad": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, väskryckning ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "stöld, utan inbrott, väskryckning mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "subventionsmissbruk": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "svikande av försvarsplikt": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap."],
  },
  "synnerligen grov misshandel": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 6 §"],
  },
  "ta del av utbildning för terrorism eller särskilt allvarlig brottslighet": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "tagande av muta": {
    sakomrade: "Tjänstebrott",
    primart_lagrum: ["BrB 20 kap."],
  },
  "tagande av olovlig väg": {
    sakomrade: "Skadegörelsebrott",
    primart_lagrum: ["BrB 12 kap."],
  },
  "terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "terroristbrott, förberedelse till terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "terroristbrott, försök till terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "terroristbrott, stämpling till terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "terroristbrott, underlåtenhet att avslöja terroristbrott": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "tillfälligt häleri, häleriförseelse": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av ej motordrivet fortskaffningsmedel, båt": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av ej motordrivet fortskaffningsmedel, cykel (ej elcykel)": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av ej motordrivet fortskaffningsmedel, elcykel": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av motordrivet fortskaffningsmedel, annat": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av motordrivet fortskaffningsmedel, båt": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av motordrivet fortskaffningsmedel, lastbil, släpfordon, järnvägsvagn avsedd för yrkesmässig godsbefordran": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av motordrivet fortskaffningsmedel, moped": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tillgrepp av motordrivet fortskaffningsmedel, motorcykel": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "tjänstefel": {
    sakomrade: "Tjänstebrott",
    primart_lagrum: ["BrB 20 kap."],
  },
  "tjänstefel m.m.": {
    sakomrade: "Tjänstebrott",
    primart_lagrum: ["BrB 20 kap. 1 §"],
    alternativa_lagrum: ["BrB 20 kap. 3 §"],
  },
  "trolöshet mot huvudman": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9-10 kap."],
  },
  "tullbrott, vårdslös tullredovisning, icke narkotikaklassade läkemedel": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "tullbrott, vårdslös tullredovisning, övriga varor, ej alkohol- eller tobaksvaror eller icke narkotikaklassade läkemedel": {
    sakomrade: "Narkotikabrott",
    primart_lagrum: ["Narkotikastrafflagen"],
  },
  "tvegifte, olovligt ingående av äktenskap, förvanskande av familjeställning": {
    sakomrade: "Brott mot familj",
    primart_lagrum: ["BrB 7 kap."],
  },
  "underlåtenhet att föra aktiebok/hålla aktiebok tillgänglig": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "uppmaning till självmord": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "uppmaning till självmord m.m.": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap. 7 §"],
  },
  "uppror": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap."],
  },
  "uppsåtligen uppehåller sig i sverige trots beslut om utvisning": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "uppvigling": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "urkundsförfalskning": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap. 1 §"],
  },
  "utförselhäleri": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "utlandsspioneri, grovt utlandsspioneri": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "utnyttjande av barn för sexuell posering": {
    sakomrade: "Övrig speciallagstiftning",
    primart_lagrum: ["Speciallag"],
  },
  "utnyttjande av barn under genom köp av sexuell handling": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap."],
  },
  "utpressning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "vapenbrott": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen (1996:67) 9 kap."],
  },
  "vapenbrott, ej grovt, innehav av annat vapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "vapenbrott, ej grovt, innehav av automatvapen (inkl. kulsprutepistol)": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "vapenbrott, ej grovt, innehav av pistol, revolver, start-, signalvapen och tårgasvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "vapenbrott; innehav av jaktvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "vapenbrott; överlåtelse eller utlåning av skjutvapen": {
    sakomrade: "Vapenbrott",
    primart_lagrum: ["Vapenlagen"],
  },
  "vapensmuggling, ej grov, olovlig in- och utförsel, av annat vapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "vapensmuggling, ej grov, olovlig in- och utförsel, av automatvapen (inkl. kulsprutepistol)": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "vapensmuggling, ej grov, olovlig in- och utförsel, av jaktvapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "vapensmuggling, ej grov, olovlig in- och utförsel, av pistol, revolver, start-, signalvapen och tårgasvapen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "vilseledande till äktenskapsresa": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["BrB 4 kap."],
  },
  "våld mot tjänsteman": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap. 1 §"],
  },
  "våld mot tjänsteman, mot ordningsvakt": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "våld mot tjänsteman, mot polisman om våldet beräknas medföra att polismannen inte blir arbetsoförmögen eller blir arbetsoförmögen under kortare tid än ett dygn": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "våld mot tjänsteman, mot polisman om våldet beräknas medföra att polismannen är arbetsoförmögen under ett dygn eller längre tid.": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "våld mot tjänsteman, mot övriga tjänstemän": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "våldsamt motstånd": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "våldtäkt": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 1 §"],
  },
  "våldtäkt inkl. grov": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 1 §"],
  },
  "våldtäkt mot barn": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 4 §"],
  },
  "våldtäkt mot barn inkl. grov": {
    sakomrade: "Sexualbrott",
    primart_lagrum: ["BrB 6 kap. 4 §"],
  },
  "vållande till annans död": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "vållande till annans död m.m.": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 7–10 §"],
  },
  "vållande till annans död, övriga fall": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "vållande till kroppsskada": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap. 8 §"],
  },
  "vållande till kroppsskada eller sjukdom": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "vållande till kroppsskada eller sjukdom, övriga fall": {
    sakomrade: "Brott mot liv och hälsa",
    primart_lagrum: ["BrB 3 kap."],
  },
  "vårdslöshet i trafik": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "vårdslöshet i trafik, grov": {
    sakomrade: "Miljöbrott",
    primart_lagrum: ["Miljöbalken"],
  },
  "vårdslöshet med gift eller smittämne": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "vårdslöshet med hemlig uppgift": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "vårdslöshet mot borgenärer": {
    sakomrade: "Brott mot borgenärer / ekonomisk brottslighet",
    primart_lagrum: ["BrB 11 kap."],
  },
  "vårdslöst bidragsbrott mot a-kassorna och länsarbetsnämnderna/arbetsförmedlingen": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "vårdslöst bidragsbrott mot försäkringskassan": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "vårdslöst bidragsbrott mot kommunerna": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "vårdslöst bidragsbrott mot ppm, csn och migrationsverket": {
    sakomrade: "Bidragsbrott",
    primart_lagrum: ["Bidragsbrottslagen"],
  },
  "väpnat hot mot laglig ordning": {
    sakomrade: "Högmålsbrott",
    primart_lagrum: ["BrB 18 kap."],
  },
  "äktenskapstvång": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "ärekränkningsbrott; förtal, förolämpning, förtal av avliden": {
    sakomrade: "Ärekränkningsbrott",
    primart_lagrum: ["BrB 5 kap. 1–4 §"],
  },
  "övergrepp i rättssak": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "överträdelse av kontaktförbud": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["Kontaktförbudslagen"],
  },
  "överträdelse av kontaktförbud med elektronisk övervakning 4088 överträdelse av kontaktförbud": {
    sakomrade: "Brott mot frihet och frid",
    primart_lagrum: ["Kontaktförbudslagen"],
  },
  "överträdelse av tillträdesförbud vid idrottsarrangemang": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "överträdelse av vistelseförbud": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "övriga brott mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap. 8–10 §"],
  },
  "övriga brott mot 13 kap., sabotage": {
    sakomrade: "Allmänfarliga brott",
    primart_lagrum: ["BrB 13 kap."],
  },
  "övriga brott mot 14 kap. brb": {
    sakomrade: "Förfalskningsbrott",
    primart_lagrum: ["BrB 14 kap."],
  },
  "övriga brott mot 15 kap. brb, dock inte": {
    sakomrade: "Brott mot rättskipningen",
    primart_lagrum: ["BrB 15 kap."],
  },
  "övriga brott mot 16 kap. brb": {
    sakomrade: "Brott mot allmän ordning",
    primart_lagrum: ["BrB 16 kap."],
  },
  "övriga brott mot 17 kap. brb": {
    sakomrade: "Brott mot allmän verksamhet",
    primart_lagrum: ["BrB 17 kap."],
  },
  "övriga brott mot 9 kap. brb": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övriga brott mot aktiebolagslagen": {
    sakomrade: "Ekonomisk brottslighet",
    primart_lagrum: ["Speciallag"],
  },
  "övriga brott mot brottsbalken": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 9 kap. 3 §"],
    alternativa_lagrum: ["BrB 9 kap. b–10 §"],
  },
  "övriga brott mot brottsbalken 8 kap, egenmäktigt förfarande exkl. olovlig parkering på annans parkeringsplats eller på annans tomtmark, självtäkt, olovlig energiavledning": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övriga brott mot miljöbalken": {
    sakomrade: "Händelser (ej brott)",
    primart_lagrum: [],
  },
  "övriga brott mot sjölagen med fängelse i straffskalan": {
    sakomrade: "Sjöfartsbrott",
    primart_lagrum: ["Sjölagen"],
  },
  "övriga brott mot specialstraffrätten där enbart böter ingår i straffskalan samt övriga brott mot brottsbalken": {
    sakomrade: "Övriga brott",
    primart_lagrum: [],
  },
  "övriga brott mot specialstraffrätten där fängelse ingår i straffskalan": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "övriga brott mot sveriges säkerhet": {
    sakomrade: "Brott mot Sveriges säkerhet",
    primart_lagrum: ["BrB 19 kap."],
  },
  "övriga brott mot utlänningslagen": {
    sakomrade: "Tull- och smugglingsbrott",
    primart_lagrum: ["Smugglingslagen"],
  },
  "övriga dödsfall utan misstanke om brott, ej": {
    sakomrade: "Brott mot utlänningslagen",
    primart_lagrum: ["Utlänningslagen"],
  },
  "övriga sjötrafikbrott mot sjölagen, sjötrafikförordningen och vattenskoterförordningen där endast böter ingår i straffskalan": {
    sakomrade: "Sjöfartsbrott",
    primart_lagrum: ["Sjölagen"],
  },
  "övriga trafikbrott med fängelse i straffskalan": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "övriga vägtrafiksbrott mot trafikförordningen, fordonsförordningen m.fl. där endast böter ingår i straffskalan": {
    sakomrade: "Trafikbrott",
    primart_lagrum: ["Trafikbrottslagen"],
  },
  "övrigt bedrägeri, ej internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övrigt bedrägeri, ej internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övrigt bedrägeri, internationell anknytning, ej mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övrigt bedrägeri, internationell anknytning, mot": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
  "övrigt dataintrång": {
    sakomrade: "Förmögenhetsbrott",
    primart_lagrum: ["BrB 8 kap."],
  },
};
